@startuml

package "scrabbler" {
[engine] --> [core]
[engine] --> [bag]
[engine] --> [board]
[engine] --> [dictionary]
[dictionary]
[core]
[board] --> [core]
[bag] --> [core]
}

package "customs" {
[Classic]
[AwordedCrack]
}

customs <|-- scrabbler

@enduml
