@startuml

package "scrabbler" {
[engine] --> [dictionary]
[engine] --> [board]
[engine] --> [core]
[dictionary] --> [bag]
[dictionary] --> [core]
[core] --> [board]
[core] --> [dictionary]
[board] --> [bag]
[board] --> [core]
[board] --> [dictionary]
[bag] --> [core]
}
@enduml
