@startuml

package "scrabbler" {
[engine] --> [core]
[engine] --> [bag]
[engine] --> [board]
[engine] --> [dictionary]
[dictionary]
[core]
[board] --> [core]
[bag] --> [core]
[customs] --> [core]
[customs] --> [board]
[customs] --> [bag]
}

package "customs" {
[Classic]
[AwordedCrack]
}

@enduml
